name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diskimage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: install gokr-packer
      run: go get github.com/gokrazy/tools/cmd/gokr-packer

    - name: generate gokrazy disk image
      run: |
        gokr-packer -overwrite=image -target_storage_bytes=1153441792 github.com/gokrazy/breakglass github.com/gokrazy/hello

    - name: add ext4
      run: |
        loop=$(sudo losetup -f -P --show )
        sudo mkfs.ext4 -q ${loop}p3
        mkdir /tmp/evcc
        sudo mount -t auto ${loop}p3 /tmp/evcc
        sudo ssh-keygen -N '' -t rsa -f ${loop}p3/breakglass.host_key
        sudo install -m 600 ~/.ssh/id_*.pub ${loop}p3/breakglass.authorized_keys
        sudo umount ${loop}p3