name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diskimage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: install gokr-packer
      run: go get -u github.com/gokrazy/tools/cmd/gokr-packer

    - name: generate gokrazy disk image
      run: |
        ls -l /opt/hostedtoolcache/go/1.15.6/x64/src/github.com/gokrazy
        ls -l /home/runner/go/src/github.com/gokrazy
        go get github.com/gokrazy/kernel github.com/gokrazy/firmware
        go run github.com/gokrazy/tools/cmd/gokr-packer -overwrite=full.img -target_storage_bytes=1610612736 github.com/gokrazy/hello
        gokr-packer -overwrite=full.img -target_storage_bytes=1610612736 github.com/gokrazy/hello

    - name: add ext4
      run: |
        ls /dev
        mkdir /tmp/sda
        mount -o loop full.img /tmp/sda
        mkfs.ext4 -q /tmp/sda
