name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diskimage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: install gokr-packer
      run: go get github.com/gokrazy/tools/cmd/gokr-packer

    - name: generate gokrazy disk image
      run: |
        gokr-packer -overwrite_root=root.img github.com/gokrazy/hello

    - name: add ext4
      run: |
        mkdir /tmp/sda
        sudo mount full.img /tmp/sda
        # sudo mount -o loop full.img /tmp/sda
        mkfs.ext4 -q /tmp/sda
