name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  diskimage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: install gokr-packer
      run: go get github.com/gokrazy/tools/cmd/gokr-packer

    - name: generate gokrazy disk image
      run: |
        gokr-packer -overwrite_root=evcc_0.39.rootfs github.com/gokrazy/hello

    - name: add ext4
      run: |
        losetup -f -P evcc_0.39.rootfs
        mount /dev/loop0
        ls /dev/loop*
        mkfs.ext4 -q /dev/loop0s2
